/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.util.Scanner;
import com.eomcs.lms.handler.BoardHandler;
import com.eomcs.lms.handler.LessonHandler;
import com.eomcs.lms.handler.MemberHandler;
import com.eomcs.lms.util.Input;

public class App {
  public static Scanner keyScan;
  
  public static void main(String[] args) {
    keyScan = new Scanner(System.in);
    
    Input.keyScan = keyScan;
    
    LessonHandler lessonHandler = new LessonHandler();
    LessonHandler.keyScan = keyScan;
    
    MemberHandler memberHandler = new MemberHandler();
    MemberHandler.keyScan = keyScan;
    
    BoardHandler boardHandler = new BoardHandler();    
    BoardHandler boardHandler2 = new BoardHandler();
    BoardHandler.keyScan = keyScan;
    
    while (true) {
      String command = prompt();

      if (command.equals("quit")) {
        System.out.println("안녕!");
        break;
      } else if (command.equals("/lesson/add")) {
        lessonHandler.addLesson();
        
      } else if (command.equals("/lesson/list")) {
        lessonHandler.listLesson();
        
      } else if (command.equals("/member/add")) {
        memberHandler.addMember();

      } else if (command.equals("/member/list")) {
        memberHandler.listMember();
        
      } else if (command.equals("/board/add")) {
        boardHandler.addBoard();

      } else if (command.equals("/board/list")) {
        boardHandler.listBoard();
        
      } else if (command.equals("/board2/add")) {
        boardHandler2.addBoard();

      } else if (command.equals("/board2/list")) {
        boardHandler2.listBoard();

      } else {
        System.out.println("실행할 수 없는 명령입니다.");
      }

      System.out.println();

    }
  }

  public static String prompt() {
    System.out.printf("명령> ");
    return keyScan.nextLine();
  }






}
