/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
  static final int LENGTH = 10;
  static Scanner keyScan = new Scanner(System.in);

  static Lesson[] lessons = new Lesson[LENGTH];
  static int lessonsSize = 0;

  static Member[] members = new Member[LENGTH];
  static int membersSize = 0;

  static Board[] boards = new Board[LENGTH];
  static int boardsSize = 0;


  public static void main(String[] args) {
    while (true) {
      String command = prompt();

      if (command.equals("quit")) {
        System.out.println("안녕!");
        break;
      } else if (command.equals("/lesson/add")) {
        addLesson();
        
      } else if (command.equals("/lesson/list")) {
        listLesson();
        
      } else if (command.equals("/member/add")) {
        addMember();

      } else if (command.equals("/member/list")) {
        listMember();
        
      } else if (command.equals("/board/add")) {
        addBoard();

      } else if (command.equals("/board/list")) {
        listBoard();

      } else {
        System.out.println("실행할 수 없는 명령입니다.");
      }

      System.out.println();

    }
  }

  static String prompt() {
    System.out.printf("명령> ");
    return keyScan.nextLine();
  }

  static void addLesson() {
    Lesson lesson = new Lesson();

    System.out.printf("번호? ");
    lesson.no = keyScan.nextInt();
    keyScan.nextLine();

    System.out.printf("수업명? ");
    lesson.title = keyScan.nextLine();

    System.out.printf("설명? ");
    lesson.contents = keyScan.nextLine();

    System.out.printf("시작일? ");
    lesson.startDate = Date.valueOf(keyScan.nextLine());

    System.out.printf("종료일? ");
    lesson.endDate = Date.valueOf(keyScan.nextLine());

    System.out.printf("총수업시간? ");
    lesson.totalHours = keyScan.nextInt();
    keyScan.nextLine();

    System.out.printf("일수업시간? ");
    lesson.dayHours = keyScan.nextInt();
    keyScan.nextLine();

    lessons[lessonsSize++] = lesson;

    System.out.println("저장하였습니다.");
  }

  static void listLesson() {
    for (int i = 0; i < lessonsSize; i++)
      System.out.printf("%d, %-20s, %s ~ %s\n", lessons[i].no, lessons[i].title,
          lessons[i].startDate, lessons[i].endDate);
  }

  static void addMember() {
    Member member = new Member();

    System.out.printf("번호? ");
    member.no = keyScan.nextInt();
    keyScan.nextLine();

    System.out.printf("이름? ");
    member.name = keyScan.nextLine();

    System.out.printf("이메일? ");
    member.email = keyScan.nextLine();

    System.out.printf("암호? ");
    member.password = keyScan.nextLine();

    System.out.printf("사진? ");
    member.photo = keyScan.nextLine();

    System.out.printf("전화? ");
    member.tel = keyScan.nextLine();

    member.registeredDate = new Date(System.currentTimeMillis());

    members[membersSize++] = member;

    System.out.println("저장하였습니다.");
  }

  static void listMember() {
    for (int i = 0; i < membersSize; i++)
      System.out.printf("%d, %-5s, %-20s, %-15s, %s\n", members[i].no, members[i].name,
          members[i].email, members[i].tel, members[i].registeredDate);
  }

  static void addBoard() {
    Board board = new Board();

    System.out.printf("번호? ");
    board.no = keyScan.nextInt();
    keyScan.nextLine();

    System.out.printf("내용? ");
    board.contents = keyScan.nextLine();

    board.createdDate = new Date(System.currentTimeMillis());

    board.viewCount = 0;

    boards[boardsSize++] = board;

    System.out.println("저장하였습니다.");
  }

  static void listBoard() {
    for (int i = 0; i < boardsSize; i++)
      System.out.printf("%d, %-20s, %-15s, %s\n", boards[i].no, boards[i].contents,
          boards[i].createdDate, boards[i].viewCount);
  }
}
