/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
      Scanner keyScan = new Scanner(System.in);
      
      System.out.printf("번호? ");
      int no = keyScan.nextInt();
      keyScan.nextLine();
      
      System.out.printf("수업명? ");
      String title = keyScan.nextLine();
      
      System.out.printf("설명? ");
      String contents = keyScan.nextLine();
      
      System.out.printf("시작일? ");
      Date startDate = Date.valueOf(keyScan.nextLine());
      
      System.out.printf("종료일? ");
      Date endDate = Date.valueOf(keyScan.nextLine());
      
      System.out.printf("총수업시간? ");
      int totalHours = keyScan.nextInt();
      
      System.out.printf("일수업시간? ");
      int dayHours = keyScan.nextInt();
      
      System.out.println();
      
      System.out.printf("번호: %d\n", no);
      System.out.printf("수업명: %s\n", title);
      System.out.printf("설명: %s\n", contents);
      System.out.printf("기간: %s ~ %s\n", startDate, endDate);
      System.out.printf("총수업시간: %d\n", totalHours);
      System.out.printf("일수업시간: %d\n", dayHours);
    }
}
