/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
      Scanner keyScan = new Scanner(System.in);
      
      Lesson[] lessons = new Lesson[100];
      
      int i = 0;
      while (true) {
        Lesson lesson = new Lesson();
      
        System.out.printf("번호? ");
        lesson.no = keyScan.nextInt();
        keyScan.nextLine();
        
        System.out.printf("수업명? ");
        lesson.title = keyScan.nextLine();
        
        System.out.printf("설명? ");
        lesson.contents = keyScan.nextLine();
        
        System.out.printf("시작일? ");
        lesson.startDate = Date.valueOf(keyScan.nextLine());
        
        System.out.printf("종료일? ");
        lesson.endDate = Date.valueOf(keyScan.nextLine());
        
        System.out.printf("총수업시간? ");
        lesson.totalHours = keyScan.nextInt();
        keyScan.nextLine();
        
        System.out.printf("일수업시간? ");
        lesson.dayHours = keyScan.nextInt();
        keyScan.nextLine();
        
        lessons[i] = lesson;
        
        System.out.println();
        
        System.out.printf("계속 입력하시겠습니까?(Y/n) ");
        String input = keyScan.nextLine();
        
        System.out.println();
        if (input.equals("Y"))
          i++;
        if (input.equals("n")) {
          for(int j = 0; j <= i; j++) {
            System.out.printf("%d, %-20s, %s ~ %s\n", lessons[j].no, lessons[j].title, 
                lessons[j].startDate, lessons[j].endDate);
          }
          break;
        }
        
      }
      
      
    }
}
