/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.util.Scanner;
import com.eomcs.lms.handler.BoardHandler;
import com.eomcs.lms.handler.BoardHandler2;
import com.eomcs.lms.handler.LessonHandler;
import com.eomcs.lms.handler.MemberHandler;
import com.eomcs.lms.util.Input;

public class App {
  public static Scanner keyScan;
  
  public static void main(String[] args) {
    keyScan = new Scanner(System.in);
    
    Input.keyScan = keyScan;
    LessonHandler.keyScan = keyScan;
    MemberHandler.keyScan = keyScan;
    BoardHandler.keyScan = keyScan;
    BoardHandler2.keyScan = keyScan;
    
    while (true) {
      String command = prompt();

      if (command.equals("quit")) {
        System.out.println("안녕!");
        break;
      } else if (command.equals("/lesson/add")) {
        LessonHandler.addLesson();
        
      } else if (command.equals("/lesson/list")) {
        LessonHandler.listLesson();
        
      } else if (command.equals("/member/add")) {
        MemberHandler.addMember();

      } else if (command.equals("/member/list")) {
        MemberHandler.listMember();
        
      } else if (command.equals("/board/add")) {
        BoardHandler.addBoard();

      } else if (command.equals("/board/list")) {
        BoardHandler.listBoard();
        
      } else if (command.equals("/board2/add")) {
        BoardHandler2.addBoard();

      } else if (command.equals("/board2/list")) {
        BoardHandler2.listBoard();

      } else {
        System.out.println("실행할 수 없는 명령입니다.");
      }

      System.out.println();

    }
  }

  public static String prompt() {
    System.out.printf("명령> ");
    return keyScan.nextLine();
  }






}
