/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
      Scanner keyScan = new Scanner(System.in);
      
      int[] no = new int[100];
      String[] title = new String[100];
      String[] contents = new String[100];
      Date[] startDate = new Date[100];
      Date[] endDate = new Date[100];
      int[] totalHours = new int[100];
      int[] dayHours = new int[100];
      
      int i = 0;
      while (true) {
      
        System.out.printf("번호? ");
        no[i] = keyScan.nextInt();
        keyScan.nextLine();
        
        System.out.printf("수업명? ");
        title[i] = keyScan.nextLine();
        
        System.out.printf("설명? ");
        contents[i] = keyScan.nextLine();
        
        System.out.printf("시작일? ");
        startDate[i] = Date.valueOf(keyScan.nextLine());
        
        System.out.printf("종료일? ");
        endDate[i] = Date.valueOf(keyScan.nextLine());
        
        System.out.printf("총수업시간? ");
        totalHours[i] = keyScan.nextInt();
        keyScan.nextLine();
        
        System.out.printf("일수업시간? ");
        dayHours[i] = keyScan.nextInt();
        keyScan.nextLine();
        
        System.out.println();
        
        System.out.printf("계속 입력하시겠습니까?(Y/n) ");
        String input = keyScan.nextLine();
        
        System.out.println();
        if (input.equals("Y"))
          i++;
        if (input.equals("n")) {
          for(int j = 0; j <= i; j++) {
            System.out.printf("%d, %-20s, %s ~ %s\n", no[j], title[j], 
                startDate[j], endDate[j]);
          }
          break;
        }
        
      }
      
      
    }
}
