/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
      Scanner keyScan = new Scanner(System.in);
      
      final int LENGTH = 10;
      
      Lesson[] lessons = new Lesson[LENGTH];
      int lessonsSize = 0;
      
      Member[] members = new Member[LENGTH];
      int membersSize = 0;
      
      Board[] boards = new Board[LENGTH];
      int boardsSize = 0;
      
      while (true) {
        Lesson lesson = new Lesson();
        
        System.out.printf("명령> ");
        String command = keyScan.nextLine();
        
        if (command.equals("quit")) {
          System.out.println("안녕!");
          break;
        } else if (command.equals("/lesson/add")) {
          System.out.printf("번호? ");
          lesson.no = keyScan.nextInt();
          keyScan.nextLine();
          
          System.out.printf("수업명? ");
          lesson.title = keyScan.nextLine();
          
          System.out.printf("설명? ");
          lesson.contents = keyScan.nextLine();
          
          System.out.printf("시작일? ");
          lesson.startDate = Date.valueOf(keyScan.nextLine());
          
          System.out.printf("종료일? ");
          lesson.endDate = Date.valueOf(keyScan.nextLine());
          
          System.out.printf("총수업시간? ");
          lesson.totalHours = keyScan.nextInt();
          keyScan.nextLine();
          
          System.out.printf("일수업시간? ");
          lesson.dayHours = keyScan.nextInt();
          keyScan.nextLine();
          
          lessons[lessonsSize++] = lesson;
          
          System.out.println("저장하였습니다.");
          
        } else if (command.equals("/lesson/list")) {
          for (int i = 0; i < lessonsSize; i++)
            System.out.printf("%d, %-20s, %s ~ %s\n", lessons[i].no, lessons[i].title, 
                lessons[i].startDate, lessons[i].endDate);
        } else if (command.equals("/member/add")) {
          Member member = new Member();
          
          System.out.printf("번호? ");
          member.no = keyScan.nextInt();
          keyScan.nextLine();
          
          System.out.printf("이름? ");
          member.name = keyScan.nextLine();
          
          System.out.printf("이메일? ");
          member.email = keyScan.nextLine();
          
          System.out.printf("암호? ");
          member.password = keyScan.nextLine();
          
          System.out.printf("사진? ");
          member.photo = keyScan.nextLine();
          
          System.out.printf("전화? ");
          member.tel = keyScan.nextLine();
          
          member.registeredDate = new Date(System.currentTimeMillis());
          
          members[membersSize++] = member;
          
          System.out.println("저장하였습니다.");
          
        } else if (command.equals("/member/list")) {
          for(int i = 0; i < membersSize; i++) 
            System.out.printf("%d, %-5s, %-20s, %-15s, %s\n", members[i].no, members[i].name,
                members[i].email, members[i].tel, members[i].registeredDate);
        } else if (command.equals("/board/add")) {
          Board board = new Board();
          
          System.out.printf("번호? ");
          board.no = keyScan.nextInt();
          keyScan.nextLine();
          
          System.out.printf("내용? ");
          board.contents  = keyScan.nextLine();
          
          board.createdDate  = new Date(System.currentTimeMillis());
          
          board.viewCount = 0;
          
          boards[boardsSize++] = board;
          
          System.out.println("저장하였습니다.");
          
        } else if (command.equals("/board/list")) {
            for(int i = 0; i < boardsSize; i++) 
              System.out.printf("%d, %-20s, %-15s, %s\n", boards[i].no, boards[i].contents, 
                  boards[i].createdDate, boards[i].viewCount);
            
        } else {
          System.out.println("실행할 수 없는 명령입니다.");
        }
        
        System.out.println();

        
      }
      
      
    }
}
